/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.90.0
  Forc version: 0.60.0
  Fuel-Core version: 0.30.0
*/

export type { LootboxAbi } from './LootboxAbi';

export { LootboxAbi__factory } from './factories/LootboxAbi__factory';
