/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.88.0
  Forc version: 0.59.0
  Fuel-Core version: 0.26.0
*/

export type { Src20AssetAbi } from './Src20AssetAbi';

export { Src20AssetAbi__factory } from './factories/Src20AssetAbi__factory';
